image: java:8-jdk

stages:
  - build
  - test

#before_script:
  #  - echo `pwd` # debug
  #  - echo "$CI_BUILD_NAME, $CI_BUILD_REF_NAME $CI_BUILD_STAGE" # debug
#  - export GRADLE_USER_HOME=`pwd`/.gradle
#  - cd netflix-eureka-naming-server

.common-job:
  before_script:
    - cd rs-discovery
  only: &changes
    changes:
      - rs-discovery/**/*

cache:
  key: "netflix-eureka-naming-server-$CI_BUILD_REF_NAME"
  policy: push
  paths:
    - rs-discovery/.gradle/wrapper
    - rs-discovery/.gradle/caches
    - rs-discovery/build

netflix-eureka-naming-server-build:
  extends: .common-job
  stage: build
  script:
    - ./gradlew assemble
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 week
  only:
    - master

netflix-eureka-naming-server-test:
  extends: .common-job
  stage: test
  script:
    - ./gradlew check
  only:
    - master

after_script:
  - echo "End CI"

