k8s_yaml('./k8s/frontend_depl.yaml')
k8s_resource('relay-service-frontend', port_forwards=3000,
    labels=['TypeScript']
)

docker_build('alexunc/rs-frontend', '.',
    build_args={'node_env': 'development'},
    entrypoint="yarn start",
    live_update=[
        sync('.', '/app'),
        run('cd /app && yarn install  --frozen-lockfile', trigger=['./package.json', './yarn.lock'])

])
