server:
  port: 8082
spring:
  application:
    name: relay-service
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: example
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    show-sql: true
    database-platform:
logging:
  file: logs/relay-service.log
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: metrics,prometheus
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
