server:
  port: 8082
spring:
  application:
    name: relay-service
  datasource:
    url: jdbc:postgresql://192.168.1.150:5432/postgres
    username: user
    password: example
  jpa:
    #    hibernate:
    #      ddl-auto: create-drop
    database: postgresql
    show-sql: true
    database-platform:
  zipkin:
    baseUrl:
      'http://localhost:9411'
  flyway:
    sql-migration-prefix: V
    repeatable-sql-migration-prefix: R
    sql-migration-separator: __
    sql-migration-suffixes: .sql
    enabled: true

logging:
  file:
    name: logs/relay-service.log
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: metrics,prometheus
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
feign:
  hystrix:
    enabled: true
