stages:
  - build
  - test

include:
  - local: 'account-management/.gitlab-ci.yml'
  - local: 'data-service/.gitlab-ci.yml'
  - local: 'user-service/.gitlab-ci.yml'
  - local: 'netflix-eureka-naming-server/.gitlab-ci.yml'
