apiVersion: skaffold/v2beta9
kind: Config
metadata:
  name: default
build:
  local:
    push: false
  artifacts:
    - image: alexunc/data-service
      context: data-service
      jib: { }
    - image: alexunc/rs-frontend
      context: frontend
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.js'
            dest: .
  tagPolicy:
    gitCommit: { }
deploy:
  #  TODO try to order configs and helm charts.
  #  ./k8s/manifests
  #  ./k8s/charts
  kubectl:
    manifests:
      - ./k8s/namespace-dev.yaml
      - ./data-service/k8s/*
      - ./frontend/infra/*
  #      - ./comments-service/infra/*
  helm:
    releases:
      - name: postgres
        namespace: default
        chartPath: ./helm/postgresql
        valuesFiles:
          - ./data-service/k8s_pg/pg_values.yaml
        wait: true
