apiVersion: skaffold/v2alpha1
kind: Config
metadata:
  name: alexunc/data-service
build:
  artifacts:
    - image: alexunc/data-service
      context: ./data-service
      jib: { }
  tagPolicy:
    gitCommit: { }
deploy:
  kubectl:
    manifests:
      - ./data-service/k8s
