image: openjdk:11-jdk-slimsdk

stages:
  - build
  - test
  - analyze

#before_script:
#  #  - echo `pwd` # debug
#  #  - echo "$CI_BUILD_NAME, $CI_BUILD_REF_NAME $CI_BUILD_STAGE" # debug
#  - export GRADLE_USER_HOME=`pwd`/.gradle
#  - cd data-service

.ds-common-job:
  before_script:
    - cd data-service
  only: &changes
    changes:
      - data-service/**/*
cache:
  key: "data-service-$CI_BUILD_REF_NAME"
  policy: push
  paths:
    - data-service/.gradle/wrapper
    - data-service/.gradle/caches
    - data-service/build

data-service-build:
  extends: .ds-common-job
  stage: build
  script:
    - ./gradlew assemble
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 week
  only:
    - master

data-service-test:
  extends: .ds-common-job
  stage: test
  script:
    - ./gradlew check
  only:
    - master

data-service-analyse:
  extends: .ds-common-job
  stage: analyze
  script:
    - ./gradlew jacocoTestReport sonarqube
  only:
    - master
after_script:
  - echo "End CI"


