image: openjdk:11-jdk-slim

stages:
  - build
  - test

#before_script:
  #  - echo `pwd` # debug
  #  - echo "$CI_BUILD_NAME, $CI_BUILD_REF_NAME $CI_BUILD_STAGE" # debug
#  - export GRADLE_USER_HOME=`pwd`/.gradle

.common:
  before_script:
    - cd cloud-api-gateway
  only: &changes
    changes:
      - user-service/**/*

cache:
  key: "cloud-api-gateway-$CI_BUILD_REF_NAME"
  policy: push
  paths:
    - cloud-api-gateway/.gradle/wrapper
    - cloud-api-gateway/.gradle/caches
    - cloud-api-gateway/build

cloud-api-gateway-build:
  extends: .common
  stage: build
  script:
    - ./gradlew assemble
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 week
  only:
    - master

cloud-api-gateway-test:
  extends: .common
  stage: test
  script:
    - ./gradlew check
  only:
    - master

after_script:
  - echo "End CI"

