{ { - if .Values.serviceAccount.create - } }
apiVersion: v1
kind: ServiceAccount
metadata:
  name: { { include "relay-service.serviceAccountName" . } }
  labels:
    { { - include "relay-service.labels" . | nindent 4 } }
  { { - with .Values.serviceAccount.annotations } }
  annotations:
    { { - toYaml . | nindent 4 } }
  { { - end } }
  { { - end } }
