docker_build('alexunc/data-service', '.')
k8s_yaml([
'../k8s/data-service-deployment.yaml',
##'../k8s/mongodb-deployment.yaml'
]
, allow_duplicates=False
)
load('ext://helm_remote', 'helm_remote')
helm_remote('postgresql',
            repo_name='pg-data-service',
            repo_url='https://charts.bitnami.com/bitnami',
            values=['k8s_pg/pg_values.yaml'])

k8s_resource('data-service', port_forwards=8080)