image: openjdk:11-jdk-slim

stages:
  - build
  - test

#before_script:
  #  - echo `pwd` # debug
  #  - echo "$CI_BUILD_NAME, $CI_BUILD_REF_NAME $CI_BUILD_STAGE" # debug
#  - export GRADLE_USER_HOME=`pwd`/.gradle
#  - cd user-service

.user-service:
  before_script:
    - cd user-service
  only: &changes
    changes:
      - user-service/**/*

cache:
  key: "user-service-$CI_BUILD_REF_NAME"
  policy: push
  paths:
    - user-service/.gradle/wrapper
    - user-service/.gradle/caches
    - user-service/build

user-service-build:
  extends: .user-service
  stage: build
  script:
    - ./gradlew assemble
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 week
  only:
    - master

user-service-test:
  extends: .user-service
  stage: test
  script:
    - ./gradlew check
  only:
    - master

after_script:
  - echo "End CI"

