spring:
  data:
    mongodb:
      username: alex
      password: password
      host: localhost
      port: 27017
      database: test
      authentication-database: admin
  threads:
    virtual:
      enabled: on

server:
  port: 8088