#spring:
#  datasource:
#    url:
#    username: 
#    password:
#  jpa:
#    hibernate:
#      ddl-auto: validate
#    database: postgresql
#    show-sql: true
#    database-platform: 
spring:
  data:
    mongodb:
      database: jsa_mongodb
      port: 27017
      host: 127.0.0.1
