spring:
  application:
    name: relay-service
  datasource: 
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: example
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    show-sql: true
    database-platform: 
logging:
  file: logs/relay-service.log

