spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: file:///home/juncevich/IdeaProjects/relay-system/git-localconfig-repo
server:
  port: 8888
