spring:
  application:
    name: cloud-api-gateway
  zipkin:
    baseUrl:
      'http://localhost:9411'
#  cloud:
#    gateway:
#      routes:
#        - id: data_service
#          uri: lb://data_service
#          predicates:
#            - Path=/data/**
server:
  port: 8765

#eureka:
#  client:
#    service-url:
#      defaultZone: http://${discovery.service.url:localhost}:8761/eureka
#  instance:
#    prefer-ip-address: true
#    ip-address: 127.0.0.1

management:
  endpoints:
    web:
      exposure:
        include: [ 'beans','health','routes','httptrace' ]
