spring:
  application:
    name: cloud-api-gateway
server:
  port: 8765
#zuul.prefix=api/
#logging:
#  level: org.springframework=info
eureka:
  client:
    service-url:
      defaultZone: http://${discovery.service.url:localhost}:8761/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
api:
  login:
    url:
      path: /user-service/users/login
  registration:
    url:
      path: /user-service/users
  h2console:
    url:
      path: /user-service/h2-console/**
  zuul:
    actuator:
      url:
        path: /actuator/*
authorization:
  token:
    header:
      name: Authorization
      prefix: Bearer
token:
  secret: adsf68768asdfuiyewrh3927dslfj

management:
  endpoints:
    web:
      exposure:
        include: ['beans','health','routes','httptrace']
