name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Grant execute permission for config-server gradlew
        run: chmod +x ./gradlew
        working-directory: config-server
      - name: Build config-server with Gradle
        run: ./gradlew assemble
        working-directory: config-server
      - name: Run tests in config-server
        run: ./gradlew check
        working-directory: config-server
