name: Java CI

on: [ push ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Grant execute permission for data-service gradlew
        run: chmod +x ./gradlew
        working-directory: data-service
      - name: Build data-service with Gradle
        run: ./gradlew assemble
        working-directory: data-service
      - name: Run tests in data-service
        run: ./gradlew check
        working-directory: data-service
