name: Data Service Java CI

on:
  push:
    branches:
      - master

defaults:
  run:
    working-directory: data-service
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 16
        uses: actions/setup-java@v1
        with:
          java-version: 16
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Build with Gradle
        run: gradle build
      - name: Generate test report
        run: gradle jacocoTestReport
      - name: Sonar analyse
        run: gradle sonarqube
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_DATA_SERVICE_TOKEN: ${{ secrets.SONAR_CLOUD_TOKEN }}
  docker:
    name: Publish to Docker Hub
    runs-on: ubuntu-latest
    needs: [ build ]
    env:
      REPO: ${{ secrets.DOCKER_REPO }}

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up JDK 16
        uses: actions/setup-java@v1
        with:
          java-version: 16
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }}
      - name: List available artifacts
        run: ls build/libs/
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USER }}/$REPO:latest .
      - name: Publish Docker image
        run: docker push ${{ secrets.DOCKER_USER }}/$REPO:latest
