name: Data Service Java CI

on:
  push:
    branches:
      - master

defaults:
  run:
    working-directory: data-service
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 16
        uses: actions/setup-java@v1
        with:
          java-version: 16
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Build with Gradle
        run: gradle build
      - name: Display structure of downloaded files
        run: ls -R
      - uses: actions/upload-artifact@v2
        with:
          name: builded-service
          path: ./
          if-no-files-found: error
      - name: Generate test report
        run: gradle jacocoTestReport
      - name: Sonar analyse
        run: gradle sonarqube
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_DATA_SERVICE_TOKEN: ${{ secrets.SONAR_CLOUD_TOKEN }}
  docker:
    name: Publish to Docker Hub
    runs-on: ubuntu-latest
    needs: [ build ]
    env:
      REPO: ${{ secrets.DOCKER_REPO }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: builded-service
          path: builded
      - name: Display structure of downloaded files
        run: ls -R
      #      - name: Set up JDK 16
      #        uses: actions/setup-java@v1
      #        with:
      #          java-version: 16
      #      - name: Cache Gradle packages
      #        uses: actions/cache@v2
      #        with:
      #          path: ~/.gradle/caches
      #          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
      #          restore-keys: ${{ runner.os }}-gradle
      #      - name: Build with Gradle
      #        run: gradle build
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }}
      - name: Print current directory
        run: pwd
      - name: Current directory files list
        run: ls -ahl
      - name: List available artifacts
        run: ls build/libs/
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USER }}/$REPO:latest .
      - name: Publish Docker image
        run: docker push ${{ secrets.DOCKER_USER }}/$REPO:latest
