name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Enter to datat-service directory
      run: cd data-service
    - name: Grant execute permission for data-service gradlew
      run: chmod +x ./gradlew
    - name: Build data-service with Gradle
      run: ./gradlew assemble
    - name: Run tests in data-service
      run: ./gradlew check
